// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgoWz1lwNGhunRzCl-qtgALZcctfGF_xI',
    appId: '1:746136349673:web:fbc2cd5a8732420a33f978',
    messagingSenderId: '746136349673',
    projectId: 'programolur',
    authDomain: 'programolur.firebaseapp.com',
    storageBucket: 'programolur.firebasestorage.app',
    measurementId: 'G-FFRZY8G332',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7wOgjs-MA6MoJZSByUGenITGSygnF5Jc',
    appId: '1:746136349673:android:835e0c22d385ef8933f978',
    messagingSenderId: '746136349673',
    projectId: 'programolur',
    storageBucket: 'programolur.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5aOqKXyzOjJhcb-UHqhXx5rl2NP3ODsk',
    appId: '1:746136349673:ios:a314ffd1543516ab33f978',
    messagingSenderId: '746136349673',
    projectId: 'programolur',
    storageBucket: 'programolur.firebasestorage.app',
    iosBundleId: 'com.example.lustrousLux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5aOqKXyzOjJhcb-UHqhXx5rl2NP3ODsk',
    appId: '1:746136349673:ios:a314ffd1543516ab33f978',
    messagingSenderId: '746136349673',
    projectId: 'programolur',
    storageBucket: 'programolur.firebasestorage.app',
    iosBundleId: 'com.example.lustrousLux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgoWz1lwNGhunRzCl-qtgALZcctfGF_xI',
    appId: '1:746136349673:web:08010643e6e8514433f978',
    messagingSenderId: '746136349673',
    projectId: 'programolur',
    authDomain: 'programolur.firebaseapp.com',
    storageBucket: 'programolur.firebasestorage.app',
    measurementId: 'G-5PESBQ6SLN',
  );

}